const state={dashboard:null,rows:[]};
const $=(selector)=>document.querySelector(selector);
const icons={total:'<svg viewBox="0 0 24 24"><path d="M6 2h9l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/></svg>',fail:'<svg viewBox="0 0 24 24"><path d="M12 3 2 21h20L12 3zM12 9v5M12 18h.01"/></svg>',possible:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4M11 8v3M11 14h.01"/></svg>',manual:'<svg viewBox="0 0 24 24"><path d="M4 5h16M4 12h16M4 19h10"/></svg>',pass:'<svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"/></svg>'};
const statusMeta={fail:{label:'规则异常',tone:'red'},possible:{label:'有造假可能',tone:'amber'},manual:{label:'待人工核验',tone:'blue'},pass:{label:'自动项通过',tone:'green'},not_applicable:{label:'不适用',tone:'slate'}};
const variantMeta={online_personal:'网银查询版个人征信',scanned_online_personal:'网银个人征信扫描件',pboc_print_personal:'人行打印版个人征信',online_enterprise:'网银查询版法人征信',leasing_enterprise:'租赁公司查询版法人征信',scanned_enterprise:'法人征信扫描件',unknown:'版本待确认'};
const formatMeta={original_electronic:'原始/电子PDF',scanned_or_image:'扫描或图片版',unknown:'形态待确认'};
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function go(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if(view==='documents')renderDocuments()}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>go(button.dataset.view));document.querySelectorAll('[data-jump-view]').forEach(button=>button.onclick=()=>go(button.dataset.jumpView));
$('#theme-toggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('veridoc-client-theme',next)};
function metricCard(label,value,detail,key,tone){return `<button class="metric tone-${tone}" data-status-filter="${key||''}"><span class="icon">${icons[key||'total']}</span><span class="label">${label}</span><strong class="value">${value}</strong><small>${detail}</small></button>`}
function countsText(row){const c=row.rule_counts||{};return `异常 ${c.fail||0} · 可能 ${c.possible||0} · 待核 ${c.manual||0} · 通过 ${c.pass||0}`}
function firstFinding(row){const item=(row.findings||[])[0];return item?`${item.rule_id} ${item.title}`:'适用自动规则未发现异常'}
function renderDashboard(data){state.dashboard=data;$('#hero-total').textContent=data.total;$('#hero-exception').textContent=data.status_counts.fail;$('#updated-at').textContent=data.generated_at?new Date(data.generated_at).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'结果已加载';$('#metrics').innerHTML=metricCard('征信报告总量',data.total,'当前专项核验范围','', 'blue')+metricCard('规则异常',data.status_counts.fail,'“提示造假”规则存在明确不一致','fail','red')+metricCard('有造假可能',data.status_counts.possible,'“有造假可能”规则存在属性偏离','possible','amber')+metricCard('待人工核验',data.status_counts.manual,'需结合原件或辅助资料进一步确认','manual','blue');document.querySelectorAll('[data-status-filter]').forEach(el=>el.onclick=()=>{sessionStorage.setItem('credit-status-filter',el.dataset.statusFilter);go('documents')});const max=Math.max(...Object.values(data.status_counts),1);$('#risk-bars').classList.remove('loading');$('#risk-bars').innerHTML=['fail','possible','manual','pass'].map(key=>`<div class="bar-row"><span>${statusMeta[key].label}</span><div class="track"><div class="fill ${key}" style="width:${Math.round(data.status_counts[key]/max*100)}%"></div></div><strong>${data.status_counts[key]}</strong></div>`).join('');$('#reason-list').classList.remove('loading');$('#reason-list').innerHTML=data.top_findings.length?data.top_findings.map(item=>`<div class="reason"><span><b>${escapeHTML(item.rule_id)}</b> ${escapeHTML(item.label)}</span><strong>${item.count}</strong></div>`).join(''):'<div class="empty">当前没有规则异常或可能异常</div>';renderAttention(data.attention_rows||[])}
function renderAttention(rows){$('#priority-rows').innerHTML=rows.length?rows.slice(0,10).map(row=>`<tr><td>${escapeHTML(row.document_id)}</td><td><span class="badge ${row.overall_status}">${statusMeta[row.overall_status].label}</span></td><td>${countsText(row)}</td><td>${escapeHTML(firstFinding(row))}</td><td><button class="action" data-detail="${escapeHTML(row.document_id)}">查看</button></td></tr>`).join(''):'<tr><td class="empty" colspan="5">当前没有规则异常或可能异常报告</td></tr>';bindDetails()}
async function loadRows(){const response=await fetch('/api/documents?limit=2000');if(!response.ok)throw new Error('documents unavailable');const data=await response.json();state.rows=data.rows||[];return state.rows}
function renderDocuments(){const query=$('#search-filter').value.trim().toLowerCase();const selected=$('#risk-filter').value||sessionStorage.getItem('credit-status-filter')||'';$('#risk-filter').value=selected;sessionStorage.removeItem('credit-status-filter');const rows=state.rows.filter(row=>(!selected||row.overall_status===selected)&&(!query||`${row.document_id} ${(row.findings||[]).map(item=>item.rule_id+item.title+item.message).join(' ')}`.toLowerCase().includes(query)));$('#document-count').textContent=`共 ${rows.length} 份征信报告`;$('#document-rows').innerHTML=rows.length?rows.map(row=>`<tr><td><strong>${escapeHTML(row.document_id)}</strong></td><td>${escapeHTML(variantMeta[row.report_variant]||row.report_variant)}<small class="cell-sub">${escapeHTML(formatMeta[row.source_format]||row.source_format)}</small></td><td><span class="badge ${row.overall_status}">${statusMeta[row.overall_status]?.label||'待确认'}</span></td><td>${countsText(row)}</td><td>${escapeHTML(firstFinding(row))}</td><td>${row.pdf_url?`<a class="action" target="_blank" href="${encodeURI(row.pdf_url)}">预览</a>`:'—'}</td><td><button class="action" data-detail="${escapeHTML(row.document_id)}">逐条规则</button></td></tr>`).join(''):'<tr><td class="empty" colspan="7">未找到符合条件的征信报告</td></tr>';bindDetails()}
$('#search-filter').oninput=renderDocuments;$('#risk-filter').onchange=renderDocuments;
function bindDetails(){document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>openDetail(button.dataset.detail))}
async function openDetail(id){const drawer=$('#detail-drawer');drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');$('#drawer-content').innerHTML='<div class="loading">正在加载逐条规则结果…</div>';try{const response=await fetch(`/api/document?id=${encodeURIComponent(id)}`);if(!response.ok)throw new Error('detail unavailable');const row=(await response.json()).document;const groups=['fail','possible','manual','pass','not_applicable'];$('#drawer-content').innerHTML=`<div class="detail-title"><p class="eyebrow">VERIFICATION RESULTS</p><h2>${escapeHTML(row.document_id)}</h2><p>${escapeHTML(variantMeta[row.report_variant]||row.report_variant)} · ${escapeHTML(formatMeta[row.source_format]||row.source_format)}</p></div><div class="score-box"><div><span class="badge big ${row.overall_status}">${statusMeta[row.overall_status]?.label}</span></div><div><strong>${countsText(row)}</strong><p style="margin-top:10px;color:var(--muted)">异常仅在证据完整时给出；待人工核验不等于造假。</p></div></div>${groups.map(group=>{const items=(row.rule_results||[]).filter(item=>item.status===group);if(!items.length)return'';return `<section class="detail-section"><h3>${statusMeta[group].label} · ${items.length}</h3><div class="rule-list">${items.map(item=>`<article class="rule-result status-${item.status}"><div><span class="rule-id">${escapeHTML(item.rule_id)}</span><strong>${escapeHTML(item.title)}</strong><span class="badge ${item.status}">${statusMeta[item.status].label}</span></div><p>${escapeHTML(item.message)}</p><small>规则口径：${escapeHTML(item.word_level)} · ${item.mode==='automatic'?'自动核验':'需结合辅助资料确认'}</small></article>`).join('')}</div></section>`}).join('')}${row.pdf_url?`<a class="pdf-link" target="_blank" href="${encodeURI(row.pdf_url)}">打开报告原件</a>`:''}`}catch(error){$('#drawer-content').innerHTML='<div class="empty">详情加载失败，请稍后重试。</div>'}}
document.querySelectorAll('[data-close-drawer]').forEach(el=>el.onclick=()=>{$('#detail-drawer').classList.remove('open');$('#detail-drawer').setAttribute('aria-hidden','true')});document.addEventListener('keydown',event=>{if(event.key==='Escape')$('[data-close-drawer]')?.click()});
async function init(){try{const [dashboardResponse]=await Promise.all([fetch('/api/dashboard'),loadRows()]);if(!dashboardResponse.ok)throw new Error('dashboard unavailable');renderDashboard(await dashboardResponse.json());renderDocuments()}catch(error){$('#service-dot').style.background='var(--red)';$('#metrics').innerHTML='<article class="panel empty">Word规则结果暂时不可用，请稍后刷新。</article>';$('#risk-bars').textContent='数据加载失败';$('#reason-list').textContent='数据加载失败'}}init();
