const state={dashboard:null,rows:[]};
const $=(selector)=>document.querySelector(selector);
const icons={total:'<svg viewBox="0 0 24 24"><path d="M6 2h9l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/></svg>',priority:'<svg viewBox="0 0 24 24"><path d="M12 3 2 21h20L12 3zM12 9v5M12 18h.01"/></svg>',review:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4M11 8v3M11 14h.01"/></svg>',routine:'<svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"/></svg>'};
const statusMeta={priority:{label:'优先复核',tone:'red'},review:{label:'建议复核',tone:'amber'},routine:{label:'常规核验',tone:'green'}};
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function go(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if(view==='documents')renderDocuments()}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>go(button.dataset.view));document.querySelectorAll('[data-jump-view]').forEach(button=>button.onclick=()=>go(button.dataset.jumpView));
$('#theme-toggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('veridoc-client-theme',next)};
function metricCard(label,value,detail,key,tone){return `<button class="metric tone-${tone}" data-status-filter="${key||''}"><span class="icon">${icons[key||'total']}</span><span class="label">${label}</span><strong class="value">${value}</strong><small>${detail}</small></button>`}
function renderDashboard(data){state.dashboard=data;$('#hero-total').textContent=data.total;$('#hero-priority').textContent=data.status_counts.priority;$('#updated-at').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});$('#metrics').innerHTML=metricCard('征信报告总量',data.total,'当前专项服务内的报告数量','', 'blue')+metricCard('优先复核',data.status_counts.priority,'建议优先安排人工复核','priority','red')+metricCard('建议复核',data.status_counts.review,'存在需进一步确认的提示','review','amber')+metricCard('常规核验',data.status_counts.routine,'当前未触发较高优先级提示','routine','green');document.querySelectorAll('[data-status-filter]').forEach(el=>el.onclick=()=>{sessionStorage.setItem('credit-status-filter',el.dataset.statusFilter);go('documents')});const max=Math.max(...Object.values(data.status_counts),1);$('#risk-bars').classList.remove('loading');$('#risk-bars').innerHTML=['priority','review','routine'].map(key=>`<div class="bar-row"><span>${statusMeta[key].label}</span><div class="track"><div class="fill ${key}" style="width:${Math.round(data.status_counts[key]/max*100)}%"></div></div><strong>${data.status_counts[key]}</strong></div>`).join('');$('#reason-list').classList.remove('loading');$('#reason-list').innerHTML=data.top_evidence.length?data.top_evidence.map(item=>`<div class="reason"><span>${escapeHTML(item.label)}</span><strong>${item.count}</strong></div>`).join(''):'<div class="empty">当前暂无重点提示</div>';renderPriority(data.priority_rows||[])}
function renderPriority(rows){$('#priority-rows').innerHTML=rows.length?rows.slice(0,8).map(row=>`<tr><td>${escapeHTML(row.document_id)}</td><td><span class="badge ${row.status}">${statusMeta[row.status].label}</span></td><td><strong>${row.risk_score}</strong></td><td>${escapeHTML(row.evidence?.[0]||'待人工复核')}</td><td><button class="action" data-detail="${escapeHTML(row.document_id)}">查看</button></td></tr>`).join(''):'<tr><td class="empty" colspan="5">当前没有优先复核报告</td></tr>';bindDetails()}
async function loadRows(){const response=await fetch('/api/documents?limit=2000');if(!response.ok)throw new Error('documents unavailable');const data=await response.json();state.rows=data.rows||[];return state.rows}
function renderDocuments(){const query=$('#search-filter').value.trim().toLowerCase();const selected=$('#risk-filter').value||sessionStorage.getItem('credit-status-filter')||'';$('#risk-filter').value=selected;sessionStorage.removeItem('credit-status-filter');const rows=state.rows.filter(row=>(!selected||row.status===selected)&&(!query||`${row.document_id} ${(row.evidence||[]).join(' ')}`.toLowerCase().includes(query)));$('#document-count').textContent=`共 ${rows.length} 份征信报告`;$('#document-rows').innerHTML=rows.length?rows.map(row=>`<tr><td><strong>${escapeHTML(row.document_id)}</strong></td><td>征信报告</td><td><span class="badge ${row.status}">${statusMeta[row.status].label}</span></td><td><strong>${row.risk_score}</strong></td><td>${escapeHTML(row.evidence?.slice(0,2).join('；')||'未触发重点提示')}</td><td>${row.pdf_url?`<a class="action" target="_blank" href="${encodeURI(row.pdf_url)}">预览</a>`:'—'}</td><td><button class="action" data-detail="${escapeHTML(row.document_id)}">详情</button></td></tr>`).join(''):'<tr><td class="empty" colspan="7">未找到符合条件的征信报告</td></tr>';bindDetails()}
$('#search-filter').oninput=renderDocuments;$('#risk-filter').onchange=renderDocuments;
function bindDetails(){document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>openDetail(button.dataset.detail))}
async function openDetail(id){const drawer=$('#detail-drawer');drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');$('#drawer-content').innerHTML='<div class="loading">正在加载报告详情…</div>';try{const response=await fetch(`/api/document?id=${encodeURIComponent(id)}`);const data=await response.json();const row=data.document;$('#drawer-content').innerHTML=`<div class="detail-title"><p class="eyebrow">CREDIT REPORT</p><h2>${escapeHTML(row.document_id)}</h2><p>征信报告专项核验详情</p></div><div class="score-box"><div><span class="score-number">${row.risk_score}</span><div>风险提示值</div></div><div><span class="badge ${row.status}">${statusMeta[row.status].label}</span><p style="margin-top:10px;color:var(--muted)">该状态用于安排人工复核顺序，不直接作为真实性最终结论。</p></div></div><section class="detail-section"><h3>核验提示</h3><div class="evidence-list">${row.evidence?.length?row.evidence.map(item=>`<div class="evidence">${escapeHTML(item)}</div>`).join(''):'<div class="evidence">当前未触发重点提示，建议按标准流程完成常规复核。</div>'}</div></section>${row.pdf_url?`<a class="pdf-link" target="_blank" href="${encodeURI(row.pdf_url)}">打开报告原件</a>`:''}`}catch(error){$('#drawer-content').innerHTML='<div class="empty">详情加载失败，请稍后重试。</div>'}}
document.querySelectorAll('[data-close-drawer]').forEach(el=>el.onclick=()=>{$('#detail-drawer').classList.remove('open');$('#detail-drawer').setAttribute('aria-hidden','true')});document.addEventListener('keydown',event=>{if(event.key==='Escape')$('[data-close-drawer]')?.click()});
async function init(){try{const [dashboardResponse]=await Promise.all([fetch('/api/dashboard'),loadRows()]);if(!dashboardResponse.ok)throw new Error('dashboard unavailable');renderDashboard(await dashboardResponse.json());renderDocuments()}catch(error){$('#service-dot').style.background='var(--red)';$('#metrics').innerHTML='<article class="panel empty">核验服务暂时不可用，请稍后刷新。</article>';$('#risk-bars').textContent='数据加载失败';$('#reason-list').textContent='数据加载失败'}}init();
