#!/usr/bin/env python3
import argparse
import csv
import json
import math
import random
from collections import Counter
from pathlib import Path


FEATURES = [
    "pages",
    "size_bytes",
    "image_count",
    "smask_count",
    "large_image_count",
    "small_overlay_count",
    "font_warning_count",
    "pdf_object_count",
    "stream_count",
    "font_object_count",
    "javascript_count",
    "embedded_file_count",
    "acroform_count",
    "annotation_count",
    "creator_missing",
    "producer_missing",
    "incremental_update_count",
]


def as_float(row, name):
    try:
        return float(row.get(name) or 0.0)
    except ValueError:
        return 0.0


def load_rows(path):
    text = Path(path).read_text(encoding="utf-8", errors="replace").replace("\x00", "")
    rows = list(csv.DictReader(text.splitlines()))
    data = []
    for row in rows:
        if row.get("label") not in {"normal", "fake"}:
            continue
        label = 1 if row.get("label") == "fake" else 0
        vector = [math.log1p(as_float(row, name)) if name == "size_bytes" else as_float(row, name) for name in FEATURES]
        data.append({"id": row.get("document_id", ""), "label": label, "features": vector})
    return data


def data_warnings(rows, train_rows, val_rows):
    counts = Counter(row["label"] for row in rows)
    train_counts = Counter(row["label"] for row in train_rows)
    val_counts = Counter(row["label"] for row in val_rows)
    warnings = []
    if counts[1] < 20:
        warnings.append(f"fake_sample_count_too_small:{counts[1]}")
    if val_counts[1] < 5:
        warnings.append(f"validation_fake_count_too_small:{val_counts[1]}")
    if counts[0] and counts[1] and counts[0] / counts[1] > 10:
        warnings.append(f"class_imbalance:{counts[0]}_normal_to_{counts[1]}_fake")
    return {
        "reliability": "low" if warnings else "normal",
        "warnings": warnings,
        "total": len(rows),
        "class_counts": {"normal": counts[0], "fake": counts[1]},
        "train_class_counts": {"normal": train_counts[0], "fake": train_counts[1]},
        "val_class_counts": {"normal": val_counts[0], "fake": val_counts[1]},
        "excluded_features": ["object_risk_score"],
        "notes": [
            "object_risk_score is excluded from training because it is generated by the rule engine and would leak rule output into the model.",
            "Current validation metrics are diagnostic only; the positive class is too small for a reliable estimate.",
        ],
    }


def stratified_split(rows, val_ratio, seed):
    rng = random.Random(seed)
    by_label = {0: [], 1: []}
    for row in rows:
        by_label[row["label"]].append(row)
    train, val = [], []
    for label_rows in by_label.values():
        rng.shuffle(label_rows)
        val_count = max(1, round(len(label_rows) * val_ratio)) if len(label_rows) > 1 else 0
        val.extend(label_rows[:val_count])
        train.extend(label_rows[val_count:])
    rng.shuffle(train)
    rng.shuffle(val)
    return train, val


def standardize(train, rows):
    dims = len(FEATURES)
    mean = [sum(row["features"][i] for row in train) / max(len(train), 1) for i in range(dims)]
    std = []
    for i in range(dims):
        var = sum((row["features"][i] - mean[i]) ** 2 for row in train) / max(len(train), 1)
        std.append(math.sqrt(var) or 1.0)
    for row in rows:
        row["x"] = [(row["features"][i] - mean[i]) / std[i] for i in range(dims)]
    return mean, std


def sigmoid(value):
    if value >= 0:
        z = math.exp(-value)
        return 1 / (1 + z)
    z = math.exp(value)
    return z / (1 + z)


def evaluate(rows, weights, bias, threshold):
    tp = fp = tn = fn = 0
    losses = []
    scores = []
    for row in rows:
        score = sigmoid(sum(w * x for w, x in zip(weights, row["x"])) + bias)
        pred = 1 if score >= threshold else 0
        label = row["label"]
        if pred == 1 and label == 1:
            tp += 1
        elif pred == 1 and label == 0:
            fp += 1
        elif pred == 0 and label == 0:
            tn += 1
        else:
            fn += 1
        losses.append(-(label * math.log(score + 1e-9) + (1 - label) * math.log(1 - score + 1e-9)))
        scores.append({"id": row["id"], "label": label, "score": round(score, 6)})
    precision = tp / max(tp + fp, 1)
    recall = tp / max(tp + fn, 1)
    f1 = 2 * precision * recall / max(precision + recall, 1e-9)
    acc = (tp + tn) / max(len(rows), 1)
    return {
        "loss": sum(losses) / max(len(losses), 1),
        "acc": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "confusion": {"tp": tp, "fp": fp, "tn": tn, "fn": fn},
        "scores": sorted(scores, key=lambda item: item["score"], reverse=True)[:30],
    }


def choose_threshold(rows, weights, bias):
    best = {"threshold": 0.5, "f1": -1}
    for step in range(5, 96, 5):
        threshold = step / 100
        metrics = evaluate(rows, weights, bias, threshold)
        if metrics["f1"] > best["f1"]:
            best = {"threshold": threshold, "f1": metrics["f1"]}
    return best["threshold"]


def train(train_rows, val_rows, epochs, lr, l2):
    dims = len(FEATURES)
    weights = [0.0] * dims
    bias = 0.0
    counts = Counter(row["label"] for row in train_rows)
    class_weight = {
        0: len(train_rows) / max(2 * counts[0], 1),
        1: len(train_rows) / max(2 * counts[1], 1),
    }
    history = []
    for epoch in range(1, epochs + 1):
        grad_w = [0.0] * dims
        grad_b = 0.0
        for row in train_rows:
            y = row["label"]
            p = sigmoid(sum(w * x for w, x in zip(weights, row["x"])) + bias)
            err = (p - y) * class_weight[y]
            for i, x in enumerate(row["x"]):
                grad_w[i] += err * x
            grad_b += err
        n = max(len(train_rows), 1)
        for i in range(dims):
            grad_w[i] = grad_w[i] / n + l2 * weights[i]
            weights[i] -= lr * grad_w[i]
        bias -= lr * grad_b / n
        threshold = choose_threshold(train_rows, weights, bias)
        train_metrics = evaluate(train_rows, weights, bias, threshold)
        val_metrics = evaluate(val_rows, weights, bias, threshold)
        record = {
            "epoch": epoch,
            "threshold": threshold,
            "train_loss": train_metrics["loss"],
            "val_loss": val_metrics["loss"],
            "val_acc": val_metrics["acc"],
            "val_precision": val_metrics["precision"],
            "val_recall": val_metrics["recall"],
            "val_f1": val_metrics["f1"],
        }
        history.append(record)
        print(json.dumps(record, ensure_ascii=False), flush=True)
    threshold = choose_threshold(train_rows, weights, bias)
    return weights, bias, threshold, history


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--features-csv", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--epochs", type=int, default=160)
    parser.add_argument("--lr", type=float, default=0.08)
    parser.add_argument("--l2", type=float, default=0.01)
    parser.add_argument("--val-ratio", type=float, default=0.25)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    rows = load_rows(args.features_csv)
    if len(Counter(row["label"] for row in rows)) < 2:
        raise SystemExit("training requires both normal and fake labeled rows")
    train_rows, val_rows = stratified_split(rows, args.val_ratio, args.seed)
    mean, std = standardize(train_rows, train_rows + val_rows)
    weights, bias, threshold, history = train(train_rows, val_rows, args.epochs, args.lr, args.l2)
    train_metrics = evaluate(train_rows, weights, bias, threshold)
    val_metrics = evaluate(val_rows, weights, bias, threshold)
    importance = sorted(
        [{"feature": name, "weight": round(weight, 6), "abs_weight": abs(weight)} for name, weight in zip(FEATURES, weights)],
        key=lambda item: item["abs_weight"],
        reverse=True,
    )
    audit = data_warnings(rows, train_rows, val_rows)
    result = {
        "model": "standardized_logistic_regression",
        "features": FEATURES,
        "threshold": threshold,
        "train_count": len(train_rows),
        "val_count": len(val_rows),
        "class_counts": audit["class_counts"],
        "data_audit": audit,
        "train": {k: v for k, v in train_metrics.items() if k != "scores"},
        "val": val_metrics,
        "importance": importance,
        "history": history,
        "weights": weights,
        "bias": bias,
        "mean": mean,
        "std": std,
    }
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "object_classifier_metrics.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"done": True, "val_f1": val_metrics["f1"], "threshold": threshold}, ensure_ascii=False), flush=True)


if __name__ == "__main__":
    main()
